
/**
 * author          Nidheesh N
 * 
 * date            14/08/2017
 * 
 * description      Constants for salesPathService and salesPathServiceTest
 * -----------------------------------------------------------
 *  Developer           Modification Date           Comments
 *  -----------------------------------------------------------
 *  K.prashanth kumar    30/8/2017                  Last Modified
 *  M. Rizwan		 Aug-03-18		    Added two variables	
 */
public class SalespathConstants {
    
    public static final String SALESPATH_SOBJECTNAME_OPPORTUNITY= 'Opportunity';
    public static final String SALESPATH_MAPPING_RECORDTYPE_OUTCOME = 'Outcome';
    public static final String SALESPATH_MAPPING_RECORDTYPE_SALESTIP = 'Sales Tips';
    public static final String SALESPATH_MAPPING_RECORDTYPE_TASK = 'Task';
    public static final String SALESPATH_MAPPING_RECORDTYPE_DEALDOCTOR_LABEL = 'Deal_doctor';
    public static final String SALESPATH_MAPPING_RECORDTYPE_DEALDOCTER = 'Deal Doctor';
    public static final String SALESPATH_FIELDTYPE_DATE_SMALL = 'date';
    public static final String SALESPATH_FIELDTYPE_DOUBLE_SMALL = 'double';
    public static final String SALESPATH_FIELDTYPE_CURRENCY_SMALL = 'currency';
    public static final String SALESPATH_FIELDTYPE_REFERENCE_SMALL = 'reference';
    public static final String SALESPATH_FIELDTYPE_PERCENT_SMALL = 'percent';
    public static final String SALESPATH_FIELDTYPE_BOOLEAN_SMALL = 'boolean';
    public static final String SALESPATH_FIELDTYPE_PICKLIST_SMALL = 'picklist';
    public static final String SALESPATH_FIELDTYPE_MULTIPICKLIST_SMALL = 'multipicklist';
    public static final String SALESPATH_FIELDTYPE_PICKLIST = 'PICKLIST';
    public static final String SALESPATH_FIELDTYPE_DATE = 'DATE';
    public static final String SALESPATH_FIELDTYPE_DATETIME = 'DATETIME';
    public static final String SALESPATH_FIELDTYPE_BOOLEAN = 'BOOLEAN';
    public static final String SALESPATH_FIELDTYPE_PERCENT = 'PERCENT';
    public static final String SALESPATH_FIELDTYPE_CURRENCY = 'CURRENCY';
    public static final String SALESPATH_FIELDTYPE_DOUBLE = 'DOUBLE';
    public static final String SALESPATH_FIELDTYPE_MULTIPICKLIST = 'MULTIPICKLIST';
    public static final String SALESPATH_FIELDTYPE_REFERNCE = 'REFERENCE';
    public static final String SALESPATH_SUCCESSMESSGE = 'Success';
    public static final String SALESPATH_COMPLETESTRING = 'Completed';
    public static final String SALESPATH_STATUS_NOTSTARTED = 'Not Started';
    public static final String SALESPATH_SALESPATHDATAWRAPPER_COMPLETEVALUE = 'Complete';
    public static final String SALESPATH_SALESPATHDATAWRAPPER_INCOMPLETEVALUE = 'incomplete';
    public static final String SALESPATH_STAGECLOSED = 'Closed';
    public static final String SALESPATH_STAGECLOSEDWON = '10 - Closed - Won';
    public static final String SALESPATH_ACTIVE = 'Active';
    public static final Decimal SALESPATH_ZEROVALUE = 0.00;
    public static final String SALESPATH_MAPPING_VOUCHER = 'Voucher';
    public static final String SALESPATH_MAPPING_PA = 'PA-220';
    public static final String SALESPATH_MAPPING_BATTLECARD = 'Battle Card';
    public static final String SALESPATH_MAPPING_VM100 = 'VM-100';
    public static final String SALESPATH_DEPENDEDPICKLIST_BASE64CHARS = '' + 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' + 'abcdefghijklmnopqrstuvwxyz' + '0123456789+/';
    //public static final String SALESPATH_TEST_FIELDSETNAME = 'global_majors_open_qualified';
   //public static final String SALESPATH_TEST_FIELDSETNAME1 = 'Global_Majors_Open_Qualified_NFRseller';
    //public static final String SALESPATH_TEST_FIELDSETNAME2 = 'Renewal_9_Submit_for_Purchasing';
    public static final String DEAL_DOCTOR_CLAIM_URL_BASE_PATH = '/a0g/e?RecordType=';
    public static final String SALESPATH_MAPPING_STATUS_INACTIVE = 'Inactive';
}